# -*- coding: utf-8 -*-
"""cpg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UcrdG_S7ztc960Bjj-nzdL8lyD5IATnT
"""

from py2neo import Graph

graph = Graph("http://localhost:7474", auth=("neo4j", "joern"))
query = """
MATCH (m:METHOD)
RETURN m.name
"""

methods = graph.run(query).data()
for method in methods:
    print(method['m.name'])


import os
import subprocess

def generate_cpg(source_code_dir, output_dir):
    """
    Generates a Code Property Graph (CPG) for the source code in source_code_dir and saves it to output_dir.

    :param source_code_dir: Path to the directory containing source code files.
    :param output_dir: Path to the directory where the CPG file will be saved.
    """
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    cpg_file = os.path.join(output_dir, "cpg.bin")
    subprocess.run(["joern-parse", "--output", cpg_file, source_code_dir])

    print(f"CPG generated and saved to {cpg_file}")


source_code_directory = "C:\Users\sigma\dataset"
output_directory = "C:\Users\sigma\.."

generate_cpg(source_code_directory, output_directory)