# -*- coding: utf-8 -*-
"""evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UcrdG_S7ztc960Bjj-nzdL8lyD5IATnT
"""

import torch
from bjxnet_model import bjXnet

def evaluate(model, test_loader):
    model.eval()
    accuracy, mrr, map_score = 0, 0, 0
    with torch.no_grad():
        for bug_vec, source_vec, label in test_loader:
            output = model(bug_vec, source_vec, graph=None, node_features=None)
            pass

    print(f'Accuracy: {accuracy}, MRR: {mrr}, MAP: {map_score}')

if __name__ == '__main__':
    model = bjXnet(...)
    evaluate(model, test_loader=None)